server:
  port: 8000

eureka:
  instance:
    hostname: localhost # ?? eureka ??
  client:
    registerWithEureka: false # ???????????
    fetchRegistry: false # ??????????? eureka ????
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #??????????