spring:
  profiles:
    active: production
management:
  endpoint:
    health:
      show-details: always
---
spring:
  profiles:
    include: production
  datasource:
    url: jdbc:mysql://localhost:3306/springroad?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sevenluo
  jpa:
    # Spring Boot2.x 开始Hibernate创建数据库默认是MyISAM引擎，需要切换回InnoDB模式引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/
  redis:
    port: 6379
    password:
    host: 127.0.0.1
  cache:
    type: redis                    # 指定cache类型
    cache-names: demoCache         # 设置cache名称
