spring:
  profiles:
    active: production
management:
  endpoint:
    health:
      show-details: always
---
spring:
  profiles:
    include: production
  datasource:
    url: jdbc:mysql://localhost:3306/springroad?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sevenluo
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/
