server:
  port: 8081

# 加入 actuator 依赖后，添加 info 终端显示信息
info:
  auth: qige
  app.name: eurekaclient
  app.desc: test eureka client
  company.name: com.qige
  company.addr: ShenZhen China

eureka:
  client:
    serviceUrl:
      # 指定 eureka 注册中心
      defaultZone: http://localhost:8000/eureka/

  instance:
    # 指定当前客户端在注册中心的名称
    instance-id: eurekaclient-8081
    # 设置客户端每 1 秒向服务端发送一次心跳
    lease-renewal-interval-in-seconds: 1
    # 设置客户端多久不向服务端发送心跳，就可以让服务端认为当前客户端已经挂了，默认 90s
    lease-expiration-duration-in-seconds: 3

spring:
  application:
    name: eurekaclient-privoder # 指定当前微服务向外暴露名称

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 开启 shutdown 命令
  endpoint:
    shutdown:
      enabled: true


